include:
  - package:flutter_lints/flutter.yaml
  - ./analysis_extra.yaml

analyzer:
  exclude:
    - lib/src/github_gql/__generated__/*.g.dart
    - lib/src/github_gql/__generated__/*.gql.dart
    - lib/src/github_gql_schema/__generated__/*.g.dart
    - lib/src/github_gql_schema/__generated__/*.gql.dart
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
