name: github_app
description: A new Flutter macOS desktop app. Integrating GitHub GraphQL Client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  gql: ^0.14.0
  gql_exec: ^0.4.3
  gql_http_link: ^0.4.5
  gql_link: ^0.5.1
  http: ^0.13.5
  oauth2: ^2.0.1
  url_launcher: ^6.1.10
  window_to_front:
    path: window_to_front
  fluttericon: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  gql_build: ^0.7.0

flutter:
  uses-material-design: true
