name: window_to_front
description: A new flutter plugin project.
version: 0.0.1
# homepage:

environment:
  sdk: ^3.0.1
  flutter: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowToFrontPlugin
      macos:
        pluginClass: WindowToFrontPlugin
      windows:
        pluginClass: WindowToFrontPlugin
